# Check for mandatory parameters

- fail: msg="kb_proxy_port must be specified and cannot be blank when kb_proxy_host is defined"
  when: (kb_proxy_port is not defined or kb_proxy_port == '') and (kb_proxy_host is defined and kb_proxy_host != '')

- debug: msg="WARNING - It is recommended you specify the parameter 'server.port'"
  when: kb_config['server.port'] is not defined

#Check if working with security we have an kb_api_basic_auth_username and kb_api_basic_auth_username - otherwise any http calls wont work
- fail: msg="Enabling security requires an kb_api_basic_auth_username and kb_api_basic_auth_password to be provided to allow cluster operations"
  when: kb_enable_xpack  and (kb_config['elasticsearch.user'] is not defined or kb_config['elasticsearch.user'] is not defined)

- set_fact: file_reserved_users={{ kb_users.file.keys() | intersect (reserved_xpack_users) }}
  when: kb_users is defined and kb_users.file is defined and (kb_users.file.keys() | length > 0) and (kb_users.file.keys() | intersect (reserved_xpack_users) | length > 0)


- set_fact: instance_default_file={{default_file | dirname}}/{{kb_instance_name}}_{{default_file | basename}}
- set_fact: instance_init_script={{init_script | dirname }}/{{kb_instance_name}}_{{init_script | basename}}  
#Use systemd for the following distributions:
#Ubuntu 15 and up
#Debian 8 and up
#Centos 7 and up
#Relies on kibana distribution installing a serviced script to determine whether one should be copied.

- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- set_fact: instance_sysd_script={{sysd_script | dirname }}/{{kb_instance_name}}_{{sysd_script | basename}}
  when: use_system_d
#For directories we also use the {{inventory_hostname}}-{{ kb_instance_name }} - this helps if we have a shared SAN.

- set_fact: instance_suffix={{inventory_hostname}}-{{ kb_instance_name }}
- set_fact: pid_dir={{ kb_pid_dir }}/{{instance_suffix}}
- set_fact: log_dir={{ kb_log_dir }}/{{instance_suffix}}
- set_fact: conf_dir={{ kb_conf_dir }}/{{ kb_instance_name }}
- set_fact: data_dirs={{ kb_data_dirs | append_to_list('/'+instance_suffix) }}
