---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: kibana-parameters.yml
  tags:
      - always

- include: kibana.yml
  tags:
      - install

- include: kibana-config.yml
  tags:
      - config


- include: kibana-plugins.yml
  when: kb_plugins is defined or kb_plugins_reinstall
  tags:
      - plugins

  #We always execute xpack as we may need to remove features
- include: xpack/kibana-xpack.yml
  tags:
      - xpack

- meta: flush_handlers

- name: Make sure kibana is started
  service: name={{instance_init_script | basename}} state=started enabled=yes
  when: kb_start_service

- name: Wait for kibana to startup
  wait_for: host={{ansible_host}} port={{kb_config['server.port']}} delay=5 connect_timeout=1
  when: kb_restarted is defined and kb_restarted.changed and kb_start_service
